repos:
- repo: local
  hooks:
    - id: test-profile
      name: test profile
      entry: poetry run python -m unittest discover tests/profile -p '*_test.py'
      pass_filenames: false
      language: system
      files: ^(pyproject.toml|poetry.lock)$

    - id: test-game-data
      name: test game data
      entry: poetry run python -m unittest discover tests/gameData -p '*_test.py'
      pass_filenames: false
      language: system
      files: ^(pyproject.toml|poetry.lock)$
