repos:
- repo: local
  hooks:
    - id: tests
      name: tests
      entry: |
        venv\\Scripts\\activate.bat
        python -m unittest discover tests/gameData -p '*_test.py'
        python -m unittest discover tests/profile -p '*_test.py'
      types: [python]
      pass_filenames: false
      language: system
      always_run: true
